lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600  # Token expires in 1 hour
    token_extractors:
        authorization_header: 
            enabled: true
            name: x-auth-token  # Specify the name of the header you want to use
            prefix: ''
        
