lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'   # Path to your private key
    public_key: '%kernel.project_dir%/config/jwt/public.pem'   # Path to your public key
    pass_phrase: 'your_passphrase'  # The passphrase for your private key (if you used one)
    token_ttl: 3600
    authorization_header:
        enabled: true    # The Authorization header will be used by default (Bearer token)
    query_parameter:
        enabled: false 
