nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'x-auth-token']
        expose_headers: ['Authorization', 'x-auth-token']
        max_age: 3600
    paths:
        '^/api/': ~
