nelmio_api_doc:
    documentation:
        info:
            title: CarpoolApi
            description: Carpool/api
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

    areas:
        path_patterns:
            - ^/api(?!/doc$)       # Exclude /api/doc route from API paths
            - ^/api(?!/doc.json$)
