nelmio_api_doc:
    documentation:
        info:
            title: CarpoolApi
            description: Carpool/api
            version: 1.0.0
        ui:
            enabled: true
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)         # Keep the /api/doc route for Swagger UI
            - ^/api(?!/doc.json$)
