security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
         app_user_provider:             
            entity:                 
                class: App\Entity\Personne                 
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            stateless: true
            security: false

        swagger_doc:
            pattern: ^/api/doc
            security: false
            
        swagger_json:
            pattern: ^/api/doc.json
            security: false

        public_api:
            pattern: ^/api/(login|inscription)
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS, methods: [GET, POST, OPTIONS] }
        - { path: ^/api/inscription, roles: PUBLIC_ACCESS, methods: [GET, POST, OPTIONS] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY, methods: [GET, POST, PUT, DELETE, OPTIONS] }
        - { path: ^/api/doc$, roles: PUBLIC_ACCESS, methods: [GET, OPTIONS] }
        - { path: ^/api/doc.json$, roles: PUBLIC_ACCESS, methods: [GET, OPTIONS] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10