controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_options:
  path: /api/login
  methods: [OPTIONS]
  controller: Symfony\Bundle\FrameworkBundle\Controller\AbstractController::emptyAction

