name: Symfony Tests and SonarQube Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Necessary for SonarQube to get full SCM history
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, json, pdo
        coverage: xdebug  # Changed to xdebug for code coverage
        
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
          
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Generate JWT keypair
      run: |
        mkdir -p config/jwt
        openssl genrsa -out config/jwt/private.pem -passout pass:!ChangeMe! 4096
        openssl rsa -pubout -in config/jwt/private.pem -passin pass:!ChangeMe! -out config/jwt/public.pem
        chmod 644 config/jwt/public.pem
        chmod 600 config/jwt/private.pem
      
    - name: Create SQLite database directory
      run: mkdir -p var/data
      
    - name: Create database and run migrations
      run: |
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:schema:create --env=test
      
    - name: Load fixtures
      run: php bin/console doctrine:fixtures:load --group=group3 --env=test --no-interaction
      
    - name: Execute tests via PHPUnit with coverage
      env:
        JWT_PASSPHRASE: "!ChangeMe!"
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}